//
//  FPPDFOptions.h
//  FPPDFFramework
//
//  Created by James Wei on 4/2/26.
//  Copyright (c) 2026 Flyingbee Software. All rights reserved.
//

#ifndef  _FPPDFOptions_
#define  _FPPDFOptions_

// Prevent C compiler from parsing C++ code
#ifdef __cplusplus

#include <iostream>
#include <fstream>
#include <cstring>


// The following ifdef block is the standard way of creating macros which make exporting
// from a DLL simpler. All files within this DLL are compiled with the FPCONVERTER_API
// symbol defined on the command line. This symbol should not be defined on any project
// that uses this DLL. This way any other project whose source files include this file see
// FPCONVERTER_API functions as being imported from a DLL, whereas this DLL sees symbols
// defined with this macro as being exported.
// Define cross-platform export macros
#if defined(_WIN32) || defined(WIN32)
    // Module definition
#define FPCONVERTER_DLL_NAME    TEXT("FPPDFFramework.dll")            // Component DLL name
// Windows platform (MSVC, MinGW, etc.)

#ifdef CONVERTER_EXPORTS
    // Export when compiling the DLL
#define FPCONVERTER_API __declspec(dllexport)
#else
    // Import when using the DLL
#define FPCONVERTER_API __declspec(dllimport)
#endif

#elif defined(__GNUC__) && (__GNUC__ >= 4)
    // GCC 4+ and compatible compilers (Linux, macOS, Clang, etc.)
    // Use visibility attribute to control symbol export
#define FPCONVERTER_API __attribute__((visibility("default")))
#else
    // Other platforms or compilers: No special handling (default global symbols)
#define FPCONVERTER_API
#endif

// =======================================================
// ================== PDFConstants ==================
// =======================================================

// Suggested ThreadMax settings
// Recommended values for device types
// Mobile phones/tablets 2~3
// Ordinary PC 4~6
// Number of server/high-performance CPU cores (e.g. 8)
// Low memory environment 1~2
//
// Default threads: 2-4 threads

#if defined(_WIN32) || defined(WIN32)
#define kFPDefaultThreadMax 4 
#else
#define kFPDefaultThreadMax 2 
#endif // WIN32

// Define default DPI parameter of 144 or 300 (recommended), and then reduce it later
#define kFPDefaultImageDPI 300


// =======================================================
// ================== FPPDF2WordOptions ==================
// =======================================================
typedef enum
{
    FPWordOption_Outline_Type_None = 0,   // Do not generate Outline
    FPWordOption_Outline_Type_PDF_Outline, // Generate the Outline of the PDF itself => default
    FPWordOption_Outline_Type_Detect_Outline,   // There is no PDF table of contents, and the table of contents is automatically generated by identifying the serial number/title.
}FPWordOption_Outline_Type;

typedef enum
{
    FPWordOption_HTML_LayoutMode_ExactPage = 0,   // Page View
    FPWordOption_HTML_LayoutMode_TextFlow, // Text Flow View
}FPWordOption_HTML_LayoutMode;

typedef enum
{
    FPWordOption_HTML_Package_None = 0,
    FPWordOption_HTML_Package_Zip, // Package all files as a zip file
}FPWordOption_HTML_Package;

typedef enum
{
    FPWordOption_HTML_Merge_Resource_None = 0,   // Do not merge
    FPWordOption_HTML_Merge_Resource_CSS_JS, // merge CSS+JS
    FPWordOption_HTML_Merge_Resource_CSS_JS_Small_Images, //  merge CSS+JS+Small Images
    FPWordOption_HTML_Merge_Resource_CSS_JS_All_Images, //  merge CSS+JS+Images
}FPWordOption_HTML_Merge_Resource;


typedef enum
{
    FPWordOption_HTML_NavigationBar_None = 0,   // No navigation bar
    FPWordOption_HTML_NavigationBar_PDFViewer, // default
    //FPWordOption_HTML_NavigationBar_PDFEdit, // All features - PDF Edit
    //FPWordOption_HTML_NavigationBar_PDFAnnotation, // All features - PDF Annotation
}FPWordOption_HTML_NavigationBar;


typedef enum
{
    FPWordOption_HTML_TextFlow_Paragraph_LineBreak = 0,   // Insert blank line
    FPWordOption_HTML_TextFlow_Paragraph_FristLineIndent, // first-line indent
}FPWordOption_HTML_TextFlow_Paragraph;


class FPCONVERTER_API FPPDF2WordOptions
{
public:
    FPPDF2WordOptions();
    FPPDF2WordOptions(FPPDF2WordOptions* copy);
    

    bool isTrimmingBlankSpaceCharacters;
    bool isMergeParagraphs;
    bool isNeedReplaceFont;

    FPWordOption_Outline_Type outlineType;
    bool enablePDFOutline_LikeDetect;

    bool enableShapeToImage;
    bool enableShapes2Shape;

    bool enableMergeIntersectImages;

    // === HTML Options ===
    FPWordOption_HTML_LayoutMode htmlLayoutMode;
    FPWordOption_HTML_NavigationBar htmlNavigationBar;
    FPWordOption_HTML_Merge_Resource htmlMergeResource;
    FPWordOption_HTML_Package htmlPackage;
    FPWordOption_HTML_TextFlow_Paragraph htmlTextFlowParagraph;
};
// =======================================================
// ================== FPPDF2ExcelOptions ==================
// =======================================================
typedef enum
{
    FPPDFToExcelFormatOptions_KeepOriginalFormatting = 0,
    FPPDFToExcelFormatOptions_RetainDataStructure,
    FPPDFToExcelFormatOptions_SpecialVersion,
}FPPDFToExcelFormatOption;

typedef enum
{
    FPPDFToExcelOverlapText_Auto = 0, // ,
    FPPDFToExcelOverlapText_Merge = 1, // .
    FPPDFToExcelOverlapText_Split = 2, // .
}FPPDFToExcelOverlapText;


typedef enum
{
    FPPDFToExcelThousandSeparator_Auto = 0, // automatic recognition
    FPPDFToExcelThousandSeparator_Comma, // Separate thousands with commas
    FPPDFToExcelThousandSeparator_Dot,  // Separate thousands with dots
    FPPDFToExcelThousandSeparator_Blank, // Separate thousands with spaces and represent decimal points with commas
    FPPDFToExcelThousandSeparator_Apostrophe, // Separate thousands with apostrophes and represent decimal points with commas
}FPPDFToExcelthousandSeparator;


class FPCONVERTER_API FPPDF2ExcelOptions
{
public:
    FPPDF2ExcelOptions();
    FPPDF2ExcelOptions(FPPDF2ExcelOptions* copy);

    FPPDFToExcelFormatOption excelFormatOption;
    FPPDFToExcelthousandSeparator thousandSeparator;
    bool allInOneSheet;
    bool allInOneSheetAddToRow;
    bool recognizeNumber;
    FPPDFToExcelOverlapText overlapText;
    bool collectCGPaths;
    bool collectFills;
    int isCSVPackageZip;
};
// =======================================================
// ================== FPPDF2PowerPointOptions ==================
// =======================================================
class FPCONVERTER_API FPPDF2PowerPointOptions
{
public:
};


// =======================================================
// ================== FPPDF2ImageOptions ==================
// =======================================================
typedef enum
{
    FPPDF2ImageOptions_Format_JPEG = 0, // 
    FPPDF2ImageOptions_Format_PNG,   // 
    FPPDF2ImageOptions_Format_BMP,   // 
    FPPDF2ImageOptions_Format_GIF,   // 
    FPPDF2ImageOptions_Format_TIFF,   //
    FPPDF2ImageOptions_Format_TGA,   //
    FPPDF2ImageOptions_Format_JPEG2000,   //
    FPPDF2ImageOptions_Format_Count,   //
}FPPDF2ImageOptions_Format;


class FPCONVERTER_API FPPDF2ImageOptions
{
public:
    FPPDF2ImageOptions();
    FPPDF2ImageOptions(FPPDF2ImageOptions* copy);
    
    int imageDPI;
    bool isAntiAlias; // Enable font smoothing(anti aliasing)
    FPPDF2ImageOptions_Format imageFormat;
    float imageQuality;
    char prefixName[256];
    int isPackageZip;
};


// =======================================================
// ================== FPPDF2ElementOptions ==================
// =======================================================
class FPCONVERTER_API FPPDF2ElementOptions
{
public:
    FPPDF2ElementOptions();
    FPPDF2ElementOptions(FPPDF2ElementOptions* copy);

    int isPackageZip;
    float imageQuality;
    char prefixName[256];
};

// =======================================================
// ================== FPPDFOCROptions ====================
// =======================================================
typedef enum
{
    FPPDFOCRPageSegmentationMode_OSDOnly = 0, //
    FPPDFOCRPageSegmentationMode_AutoOSD,   //
    FPPDFOCRPageSegmentationMode_AutoOnly,   //
    FPPDFOCRPageSegmentationMode_Auto,   //
    FPPDFOCRPageSegmentationMode_SingleColumn,
    FPPDFOCRPageSegmentationMode_SingleBlockVertText,
    FPPDFOCRPageSegmentationMode_SingleBlock,
    FPPDFOCRPageSegmentationMode_SingleLine,
    FPPDFOCRPageSegmentationMode_SingleWord,
    FPPDFOCRPageSegmentationMode_CircleWord,
    FPPDFOCRPageSegmentationMode_SingleChar,
    FPPDFOCRPageSegmentationMode_SparseText,
    FPPDFOCRPageSegmentationMode_SparseTextOSD,
    FPPDFOCRPageSegmentationMode_Count,
}FPPDFOCRPageSegmentationMode;

typedef enum {
    FPPDFOCREngineMode_TesseractOnly,
    FPPDFOCREngineMode_LSTM_ONLY, // Tesseract 4.0+
    FPPDFOCREngineMode_LSTM_COMBINED,
    FPPDFOCREngineMode_Default,
    FPPDFOCREngineMode_Count,
}FPPDFOCREngineMode;

class FPCONVERTER_API FPPDFOCROptions
{
public:
    FPPDFOCROptions();
    FPPDFOCROptions(FPPDFOCROptions* copy);

    unsigned int resizeDPI;
    bool isEnableImageScan; // Do you want to enable image scanning preprocessing
    FPPDFOCRPageSegmentationMode pageSegmentationMode; // not used
    FPPDFOCREngineMode engineMode;
    char language[128];
    float minConfidence; // 0.0 ~ 100.0; Default: 50;
    
};

// =======================================================
// ================== FPPDFOptions ==================
// =======================================================
typedef enum {
    FPPDFOptions_PageOrientationAuto = 0,
    FPPDFOptions_PageOrientationPortrait,
    FPPDFOptions_PageOrientationLandscape
} FPPDFOptions_PageOrientation;

typedef enum {
    FPPDFOptions_ScaleMethodFit = 0,
    FPPDFOptions_ScaleMethodFitWidth,
    FPPDFOptions_ScaleMethodFitHeight,
    FPPDFOptions_ScaleMethodReduce,
    FPPDFOptions_ScaleMethodReduceWidth,
    FPPDFOptions_ScaleMethodReduceHeight,
    FPPDFOptions_ScaleMethodNone
} FPPDFOptions_ScaleMethod;

typedef enum {
    FPPDFOptions_ScaleFitTypeWidth = 0,
    FPPDFOptions_ScaleFitTypeHeight,
    FPPDFOptions_ScaleFitTypeNone
} FPPDFOptions_ScaleFitType; // how we should actually fit the image

// FPPDFOptions
class FPCONVERTER_API FPPDFOptions {
public:
    FPPDFOptions();
    FPPDFOptions(const FPPDFOptions* other);

    ~FPPDFOptions();
    FPPDFOptions& operator=(const FPPDFOptions&) = delete;

    void setImageDPI(int dpi);

    int isTrailVersion; // Is it a trial version
    int isParserAnnots; // Whether to extract annotation information.
    int imageDPI; // DPI of images
    float imageQuality; // image quality
    int threadMax; // Number of threads used for conversion
    
    // Is the output of the conversion a file or a folder? For example: images
    bool isOutputFormatFolder; // Get - Default is file
    // Options for converting formats
    FPPDF2WordOptions* wordOptions;
    FPPDF2PowerPointOptions* powerPointOptions;
    FPPDF2ExcelOptions* excelOptions;
    FPPDF2ImageOptions* imageOptions;
    FPPDF2ElementOptions* elementOptions;
    // OCR recognize
    bool isEnableOCR; // Do you want to enable OCR text recognition
    FPPDFOCROptions* ocrOptions; // OCR settings
};

#endif // Prevent C compiler from parsing C++ code
#endif
